export type Lang = "pt" | "en" | "es" | "ar";

export const LOCALES: Lang[] = ["pt", "en", "es", "ar"];

export type TextTranslations = Record<string, Record<Lang, string>>;
export type WorkTranslationSeed = {
  title: string;
  category: string;
  technique: string;
  description: string;
};

export type WorkTranslations = Record<string, Record<Lang, WorkTranslationSeed>>;

export const textTranslations: TextTranslations = {
  hero_title: {
    pt: "ATELIER DANIEL DETOMI",
    en: "ATELIER DANIEL DETOMI",
    es: "ATELIER DANIEL DETOMI",
    ar: "مرسم دانيال ديتومي",
  },
  hero_subtitle: {
    pt: "Arte e Natureza em Tiradentes — Minas Gerais",
    en: "Art and Nature in Tiradentes — Minas Gerais",
    es: "Arte y Naturaleza en Tiradentes — Minas Gerais",
    ar: "فن وطبيعة في تيرادنتيس — ميناس جيرايس",
  },
  hero_text: {
    pt: "Um artista que não se limita a uma técnica, mas a um território criativo — onde a pintura de cavalete, a escultura, a instalação ambiental e o desenho gráfico coexistem como manifestações de uma mesma visão.\n\nAqui, a arte não fica atrás de vidro: ela cresce no jardim, emerge da encosta e caminha entre as árvores. Visite o ateliê em Tiradentes e encontre as obras entre a vegetação — como deve ser.",
    en: "An artist who is not limited to one technique, but to a creative territory — where easel painting, sculpture, environmental installation and graphic drawing coexist as expressions of the same vision.\n\nHere, art is not kept behind glass: it grows in the garden, emerges from the hillside and moves among the trees. Visit the studio in Tiradentes and encounter the works among the vegetation — as they should be.",
    es: "Un artista que no se limita a una técnica, sino a un territorio creativo — donde la pintura de caballete, la escultura, la instalación ambiental y el dibujo gráfico conviven como manifestaciones de una misma visión.\n\nAquí, el arte no queda detrás del vidrio: crece en el jardín, emerge de la ladera y camina entre los árboles. Visita el atelier en Tiradentes y encuentra las obras entre la vegetación — como debe ser.",
    ar: "فنان لا يقتصر على تقنية واحدة، بل يتحرك داخل أرض إبداعية تتجاور فيها لوحة الحامل والمنحوتة والتركيب البيئي والرسم الغرافيكي كتعبيرات عن رؤية واحدة.\n\nهنا لا يبقى الفن خلف الزجاج: إنه ينمو في الحديقة، ويخرج من المنحدر، ويتحرك بين الأشجار. زر المرسم في تيرادنتيس واكتشف الأعمال بين النباتات كما ينبغي لها أن تكون.",
  },
  home_painting_title: {
    pt: "A Pintura — o mundo lírico e o mundo gráfico",
    en: "Painting — the lyrical world and the graphic world",
    es: "La Pintura — el mundo lírico y el mundo gráfico",
    ar: "الرسم — العالم الغنائي والعالم الغرافيكي",
  },
  home_painting_text: {
    pt: "De um lado, paisagens densas, fauna e flora brasileiras em cores vibrantes — tucanos, ipês, cenas tropicais. É o Brasil imaginário de Detomi.\n\nDo outro, o dálmata, o tênis xadrez, os arlequins — um universo de ilusão de ótica, pop art e circo, que revela formação técnica rigorosa e interesse pela percepção visual.\n\nDuas faces do mesmo olhar: observar a natureza com a mesma precisão com que se deconstrói uma grade xadrez.",
    en: "On one side, dense landscapes, Brazilian fauna and flora in vibrant colors — toucans, ipês and tropical scenes. This is Detomi's imagined Brazil.\n\nOn the other, the dalmatian, the chessboard sneaker, the harlequins — a universe of optical illusion, pop art and circus that reveals rigorous technical training and a fascination with visual perception.\n\nTwo sides of the same gaze: observing nature with the same precision used to deconstruct a chessboard grid.",
    es: "Por un lado, paisajes densos, fauna y flora brasileñas en colores vibrantes — tucanes, ipês y escenas tropicales. Es el Brasil imaginario de Detomi.\n\nPor otro, el dálmata, el tenis ajedrezado, los arlequines — un universo de ilusión óptica, pop art y circo que revela formación técnica rigurosa e interés por la percepción visual.\n\nDos caras de una misma mirada: observar la naturaleza con la misma precisión con la que se deconstruye una retícula ajedrezada.",
    ar: "من جهة، مناظر كثيفة وحيوانات ونباتات برازيلية بألوان نابضة: طيور الطوقان وأشجار الإيبيه ومشاهد استوائية. إنها برازيل ديتومي المتخيلة.\n\nومن جهة أخرى، الدلماسي والحذاء ذي الرقعة الشطرنجية والهارلكين: عالم من الخداع البصري وفن البوب والسيرك يكشف تدريبًا تقنيًا صارمًا واهتمامًا بالإدراك البصري.\n\nوجهان للنظرة نفسها: مراقبة الطبيعة بالدقة ذاتها التي تفكك شبكة شطرنجية.",
  },
  home_sculpture_title: {
    pt: "A Escultura e o Recorte — o corpo na paisagem",
    en: "Sculpture and Cut-Out — the body in the landscape",
    es: "La Escultura y el Recorte — el cuerpo en el paisaje",
    ar: "النحت والقص المعدني — الجسد في المشهد",
  },
  home_sculpture_text: {
    pt: "Araras, veados, capivaras e as grandes faces na encosta são obras que só existem plenamente em relação ao lugar.\n\nNo jardim, na luz de Tiradentes, entre as plantas — cada visita ao ateliê é uma experiência de lugar, não apenas de obra.",
    en: "Macaws, deer, capybaras and the large faces on the hillside are works that only fully exist in relation to the place.\n\nIn the garden, in the light of Tiradentes, among the plants — every visit to the studio is an experience of place, not only of artwork.",
    es: "Guacamayos, venados, capibaras y los grandes rostros en la ladera son obras que solo existen plenamente en relación con el lugar.\n\nEn el jardín, en la luz de Tiradentes, entre las plantas — cada visita al atelier es una experiencia de lugar, no solo de obra.",
    ar: "الببغاوات والغزلان والكابيبارا والوجوه الكبيرة على المنحدر أعمال لا تكتمل إلا بعلاقتها بالمكان.\n\nفي الحديقة، في ضوء تيرادنتيس، بين النباتات، تصبح كل زيارة للمرسم تجربة مكان لا مشاهدة عمل فقط.",
  },
  home_alterego_title: {
    pt: "O Indígena e o Palhaço — os alter-egos",
    en: "The Indigenous Figure and the Clown — the alter egos",
    es: "El Indígena y el Payaso — los alter egos",
    ar: "الشخصية الأصلية والمهرج — الوجهان الآخران",
  },
  home_alterego_text: {
    pt: "A cabeça indígena com o cocar é um autorretrato simbólico. Os palhaços equilibristas são uma reflexão sobre o artista como performer.\n\nDetomi não é apenas um pintor de natureza: é um pensador visual.",
    en: "The Indigenous head with the headdress is a symbolic self-portrait. The balancing clowns are a reflection on the artist as performer.\n\nDetomi is not only a painter of nature: he is a visual thinker.",
    es: "La cabeza indígena con el tocado es un autorretrato simbólico. Los payasos equilibristas son una reflexión sobre el artista como performer.\n\nDetomi no es solo un pintor de naturaleza: es un pensador visual.",
    ar: "الرأس المستوحى من الشعوب الأصلية مع غطاء الرأس هو صورة ذاتية رمزية. أما المهرجون المتوازنون فهم تأمل في الفنان بوصفه مؤديًا.\n\nديتومي ليس رسامًا للطبيعة فقط، بل مفكر بصري.",
  },
  artist_bio: {
    pt: "Daniel Detomi é mineiro, nascido em São João del-Rei. Desenvolveu seu trabalho criativo na cidade histórica de Tiradentes — MG, no início dos anos 90, junto a renomados artistas como Fernando Pita e Toti (Oficina de Agosto), dentre outros.\n\nNesta cidade histórica, fez parte de um conjunto de artistas que iniciaram um movimento artístico que se desenvolve até os dias de hoje — moldando a arte mineira, valorizando a cultura, promovendo a inclusão social e a conscientização ambiental.\n\nSuas obras, de temáticas variadas, têm como foco o reúso das mais diversas matérias-primas: papel machê em homenagem aos povos originários, a fauna brasileira em recortes de chapas de metal de reúso e painéis de madeira de demolição que retratam as paisagens e belezas de um Brasil tão rico e diverso.\n\nNo Atelier Daniel Detomi — Arte e Natureza, o visitante caminha entre esculturas monumentais no jardim e pinturas nas paredes. O ateliê é um lugar físico que se visita — e este site é um convite.",
    en: "Daniel Detomi is from Minas Gerais, born in São João del-Rei. He developed his creative work in the historic town of Tiradentes, Minas Gerais, in the early 1990s, alongside renowned artists such as Fernando Pita and Toti from Oficina de Agosto, among others.\n\nIn this historic town, he was part of a group of artists who began a movement that continues to unfold today — shaping art in Minas Gerais, valuing culture, promoting social inclusion and environmental awareness.\n\nHis works, with varied themes, focus on the reuse of diverse raw materials: papier-mâché honoring Indigenous peoples, Brazilian fauna cut from reclaimed metal sheets, and demolition-wood panels portraying the landscapes and beauty of a rich and diverse Brazil.\n\nAt Atelier Daniel Detomi — Art and Nature, visitors walk among monumental sculptures in the garden and paintings on the walls. The studio is a physical place to visit — and this site is an invitation.",
    es: "Daniel Detomi es mineiro, nacido en São João del-Rei. Desarrolló su trabajo creativo en la ciudad histórica de Tiradentes, Minas Gerais, a comienzos de los años 90, junto a reconocidos artistas como Fernando Pita y Toti, de la Oficina de Agosto, entre otros.\n\nEn esta ciudad histórica formó parte de un grupo de artistas que iniciaron un movimiento artístico que se desarrolla hasta hoy — moldeando el arte de Minas Gerais, valorando la cultura, promoviendo la inclusión social y la conciencia ambiental.\n\nSus obras, de temáticas variadas, se centran en el reúso de las más diversas materias primas: papel maché en homenaje a los pueblos originarios, fauna brasileña recortada en chapas de metal reutilizado y paneles de madera de demolición que retratan los paisajes y bellezas de un Brasil rico y diverso.\n\nEn Atelier Daniel Detomi — Arte y Naturaleza, el visitante camina entre esculturas monumentales en el jardín y pinturas en las paredes. El atelier es un lugar físico que se visita — y este sitio es una invitación.",
    ar: "دانيال ديتومي فنان من ميناس جيرايس وُلد في ساو جواو دل ري. طوّر عمله الإبداعي في مدينة تيرادنتيس التاريخية في مطلع التسعينيات، إلى جانب فنانين بارزين مثل فرناندو بيتا وتوتي من Oficina de Agosto وغيرهما.\n\nفي هذه المدينة التاريخية، كان جزءًا من مجموعة فنانين أطلقت حركة فنية لا تزال تتطور حتى اليوم، وتشكل فن ميناس جيرايس وتثمّن الثقافة وتعزز الإدماج الاجتماعي والوعي البيئي.\n\nتركز أعماله، رغم تنوع موضوعاتها، على إعادة استخدام مواد متعددة: ورق معجون تكريمًا للشعوب الأصلية، وحيوانات برازيلية مقصوصة من صفائح معدنية معاد استخدامها، وألواح خشب هدم تصور مناظر البرازيل الغنية والمتنوعة.\n\nفي مرسم دانيال ديتومي — فن وطبيعة، يمشي الزائر بين منحوتات ضخمة في الحديقة ولوحات على الجدران. المرسم مكان حقيقي يُزار، وهذا الموقع دعوة إليه.",
  },
  artist_quote: {
    pt: "Do descarte nasce a obra. Da terra, a memória. Do olhar, a forma.",
    en: "From discard, the work is born. From the earth, memory. From the gaze, form.",
    es: "Del descarte nace la obra. De la tierra, la memoria. De la mirada, la forma.",
    ar: "من المهمل يولد العمل. ومن الأرض تأتي الذاكرة. ومن النظرة يتشكل الشكل.",
  },
  expo_title: {
    pt: "Exposições",
    en: "Exhibitions",
    es: "Exposiciones",
    ar: "المعارض",
  },
  expo_recortes_title: {
    pt: "RECORTES DO CERRADO",
    en: "RECORTES DO CERRADO",
    es: "RECORTES DO CERRADO",
    ar: "RECORTES DO CERRADO",
  },
  expo_recortes_text: {
    pt: "A fauna do cerrado mineiro recortada em metal de reúso: lobos-guará, onças, seriemas, capivaras e veados ocupam o espaço como quem retoma o próprio território.\n\nUma exposição que é também um alerta — preservar o cerrado é preservar tudo o que vive nele.",
    en: "The fauna of the cerrado in Minas Gerais cut from reclaimed metal: maned wolves, jaguars, seriemas, capybaras and deer occupy the space as if reclaiming their own territory.\n\nAn exhibition that is also a warning — preserving the cerrado means preserving everything that lives within it.",
    es: "La fauna del cerrado mineiro recortada en metal reutilizado: lobos de crin, jaguares, seriemas, capibaras y venados ocupan el espacio como quien retoma su propio territorio.\n\nUna exposición que también es una alerta: preservar el cerrado es preservar todo lo que vive en él.",
    ar: "حيوانات سيرادو ميناس جيرايس مقصوصة من معدن معاد استخدامه: ذئاب الغوارا والنمور والسيريما والكابيبارا والغزلان تحتل المكان كأنها تستعيد أرضها.\n\nمعرض هو أيضًا تنبيه: الحفاظ على السيرادو يعني الحفاظ على كل ما يعيش فيه.",
  },
  expo_terra_title: {
    pt: "TERRA BRASILIS",
    en: "TERRA BRASILIS",
    es: "TERRA BRASILIS",
    ar: "TERRA BRASILIS",
  },
  expo_terra_text: {
    pt: "Papel machê em homenagem aos povos originários, a fauna brasileira em recortes de chapas de metal de reúso e painéis de madeira de demolição retratando as paisagens e belezas do Brasil.\n\nUma mostra que valoriza a cultura, promove a inclusão social e a conscientização ambiental.",
    en: "Papier-mâché honoring Indigenous peoples, Brazilian fauna cut from reclaimed metal sheets, and demolition-wood panels portraying Brazil's landscapes and beauty.\n\nA show that values culture, promotes social inclusion and encourages environmental awareness.",
    es: "Papel maché en homenaje a los pueblos originarios, fauna brasileña recortada en chapas de metal reutilizado y paneles de madera de demolición que retratan los paisajes y bellezas de Brasil.\n\nUna muestra que valora la cultura, promueve la inclusión social y la conciencia ambiental.",
    ar: "ورق معجون تكريمًا للشعوب الأصلية، وحيوانات برازيلية مقصوصة من صفائح معدنية معاد استخدامها، وألواح من خشب الهدم تصور مناظر البرازيل وجمالها.\n\nمعرض يثمّن الثقافة ويعزز الإدماج الاجتماعي والوعي البيئي.",
  },
  tiradentes_title: {
    pt: "Tiradentes — Minas Gerais",
    en: "Tiradentes — Minas Gerais",
    es: "Tiradentes — Minas Gerais",
    ar: "تيرادنتيس — ميناس جيرايس",
  },
  tiradentes_text: {
    pt: "Fundada no início do século XVIII, Tiradentes é uma das cidades históricas mais bem preservadas do Brasil. Ruas de pedra, casario colonial, igrejas barrocas e a Serra de São José emoldurando o horizonte — a cidade inteira é um cenário que inspirou gerações de artistas.\n\nFoi aqui, no início dos anos 90, que um grupo de artistas — entre eles Daniel Detomi, Fernando Pita e Toti, da Oficina de Agosto — iniciou um movimento que transformou Tiradentes, Bichinho e adjacências em um polo de arte reconhecido em todo o país.\n\nHoje, ateliês, galerias e oficinas dividem espaço com a gastronomia mineira e os festivais culturais. O Atelier Daniel Detomi — Arte e Natureza faz parte dessa história: um lugar onde a arte cresce no jardim e recebe visitantes de portas abertas.\n\nPara visitar, chame no WhatsApp {whatsapp} e agende. A placa na estrada indica o caminho — siga a seta vermelha.",
    en: "Founded in the early eighteenth century, Tiradentes is one of Brazil's best-preserved historic towns. Stone streets, colonial houses, baroque churches and the Serra de São José framing the horizon — the whole town is a setting that has inspired generations of artists.\n\nIt was here, in the early 1990s, that a group of artists — including Daniel Detomi, Fernando Pita and Toti from Oficina de Agosto — began a movement that transformed Tiradentes, Bichinho and the surrounding area into an art center recognized throughout Brazil.\n\nToday, studios, galleries and workshops share space with Minas Gerais cuisine and cultural festivals. Atelier Daniel Detomi — Art and Nature is part of this story: a place where art grows in the garden and receives visitors with open doors.\n\nTo visit, contact us on WhatsApp at {whatsapp} and schedule an appointment. The road sign points the way — follow the red arrow.",
    es: "Fundada a comienzos del siglo XVIII, Tiradentes es una de las ciudades históricas mejor preservadas de Brasil. Calles de piedra, casonas coloniales, iglesias barrocas y la Serra de São José enmarcando el horizonte — toda la ciudad es un escenario que inspiró a generaciones de artistas.\n\nFue aquí, a comienzos de los años 90, donde un grupo de artistas — entre ellos Daniel Detomi, Fernando Pita y Toti, de la Oficina de Agosto — inició un movimiento que transformó Tiradentes, Bichinho y sus alrededores en un polo de arte reconocido en todo el país.\n\nHoy, ateliers, galerías y talleres comparten espacio con la gastronomía mineira y los festivales culturales. Atelier Daniel Detomi — Arte y Naturaleza forma parte de esa historia: un lugar donde el arte crece en el jardín y recibe visitantes con puertas abiertas.\n\nPara visitar, escribe por WhatsApp al {whatsapp} y agenda. El cartel en el camino indica la dirección — sigue la flecha roja.",
    ar: "تأسست تيرادنتيس في أوائل القرن الثامن عشر، وهي من أكثر المدن التاريخية حفظًا في البرازيل. شوارع حجرية وبيوت استعمارية وكنائس باروكية وجبال سيرا دي ساو جوزيه تؤطر الأفق؛ المدينة كلها مشهد ألهم أجيالًا من الفنانين.\n\nهنا، في مطلع التسعينيات، بدأت مجموعة من الفنانين — من بينهم دانيال ديتومي وفرناندو بيتا وتوتي من Oficina de Agosto — حركة حولت تيرادنتيس وبيشينيو والمناطق المجاورة إلى مركز فني معروف في البرازيل كلها.\n\nاليوم تتجاور المراسم والمعارض والورش مع مطبخ ميناس جيرايس والمهرجانات الثقافية. مرسم دانيال ديتومي — فن وطبيعة جزء من هذه القصة: مكان ينمو فيه الفن في الحديقة ويستقبل الزوار بأبواب مفتوحة.\n\nللزيارة، تواصل عبر واتساب على الرقم {whatsapp} وحدد موعدًا. اللافتة على الطريق تدل على الاتجاه — اتبع السهم الأحمر.",
  },
  footer_tagline: {
    pt: "Arte e Natureza — Tiradentes, Minas Gerais",
    en: "Art and Nature — Tiradentes, Minas Gerais",
    es: "Arte y Naturaleza — Tiradentes, Minas Gerais",
    ar: "فن وطبيعة — تيرادنتيس، ميناس جيرايس",
  },
};

function wt(title: string, category: string, technique: string, description: string): WorkTranslationSeed {
  return { title, category, technique, description };
}

export const workTranslations: WorkTranslations = {
  camaleao: {
    pt: wt("Camaleão", "Pinturas", "Pintura sobre tela", "Um camaleão gigante enrola o rabo em espiral sobre o galho, o corpo vestido com a bandeira do Brasil: cabeça verde, tronco amarelo, e o azul estrelado correndo pelas costas.\n\nAs escamas do animal são pintadas uma a uma, com luz e sombra em cada ponta, criando um volume que parece saltar do plano.\n\nComo o camaleão, o Brasil muda de cor conforme o ambiente — mas a essência continua firme no galho. Obra vibrante, das mais pedidas por quem visita o ateliê."),
    en: wt("Camaleão", "Paintings", "Painting on canvas", "A giant chameleon curls its tail in a spiral around the branch, its body dressed in the Brazilian flag: green head, yellow torso and starry blue running along its back.\n\nThe animal's scales are painted one by one, with light and shadow at each point, creating a volume that seems to leap from the surface.\n\nLike the chameleon, Brazil changes color according to its surroundings — yet its essence remains steady on the branch. A vibrant work, among the most requested by studio visitors."),
    es: wt("Camaleão", "Pinturas", "Pintura sobre lienzo", "Un camaleón gigante enrosca la cola en espiral sobre la rama, con el cuerpo vestido con la bandera de Brasil: cabeza verde, tronco amarillo y azul estrellado corriendo por la espalda.\n\nLas escamas del animal están pintadas una a una, con luz y sombra en cada punta, creando un volumen que parece saltar del plano.\n\nComo el camaleón, Brasil cambia de color según el ambiente, pero su esencia sigue firme en la rama. Una obra vibrante, de las más solicitadas por quienes visitan el atelier."),
    ar: wt("Camaleão", "لوحات", "رسم على قماش", "حرباء عملاقة تلف ذيلها حلزونيًا حول الغصن، وجسدها يرتدي ألوان علم البرازيل: رأس أخضر وجذع أصفر وأزرق مرصع بالنجوم يمتد على الظهر.\n\nرُسمت حراشف الحيوان واحدة تلو الأخرى، مع ضوء وظل في كل طرف، لتخلق حجمًا يبدو كأنه يقفز من السطح.\n\nمثل الحرباء، تغير البرازيل لونها بحسب البيئة، لكن جوهرها يبقى ثابتًا على الغصن. عمل نابض ومن أكثر الأعمال طلبًا من زوار المرسم."),
  },
  revoada: {
    pt: wt("Revoada", "Pinturas", "Pintura sobre tela", "Papagaios verdes, araras-azuis, periquitos e tucanos dividem os galhos de um ipê florido — dezenas de aves, cada uma com pose e olhar próprios.\n\nO fundo é um degradê de verdes e azuis que sugere a mata ao longe; na frente, a explosão dourada das flores organiza o caos.\n\nO ipê floresce por poucos dias no ano. A pintura fixa para sempre esse instante em que a floresta inteira parece acesa."),
    en: wt("Revoada", "Paintings", "Painting on canvas", "Green parrots, blue macaws, parakeets and toucans share the branches of a flowering ipê — dozens of birds, each with its own pose and gaze.\n\nThe background is a gradient of greens and blues suggesting the forest in the distance; in front, the golden burst of flowers gives order to the abundance.\n\nThe ipê blooms for only a few days each year. The painting preserves forever the instant when the entire forest seems lit."),
    es: wt("Revoada", "Pinturas", "Pintura sobre lienzo", "Papagayos verdes, guacamayos azules, periquitos y tucanes comparten las ramas de un ipê florido — decenas de aves, cada una con su postura y su mirada.\n\nEl fondo es un degradado de verdes y azules que sugiere la mata a lo lejos; al frente, la explosión dorada de las flores organiza el caos.\n\nEl ipê florece pocos días al año. La pintura fija para siempre ese instante en que todo el bosque parece encendido."),
    ar: wt("Revoada", "لوحات", "رسم على قماش", "ببغاوات خضراء وببغاوات مكاو زرقاء وطيور صغيرة وطوقان تتقاسم أغصان شجرة إيبيه مزهرة؛ عشرات الطيور، لكل واحد وقفته ونظرته.\n\nالخلفية تدرج من الأخضر والأزرق يوحي بالغابة البعيدة، وفي المقدمة تنظم انفجار الزهور الذهبية هذا الثراء.\n\nتزهر الإيبيه أيامًا قليلة في السنة. تحفظ اللوحة إلى الأبد تلك اللحظة التي تبدو فيها الغابة كلها مضاءة."),
  },
  "tiradentes-panel": {
    pt: wt("Tiradentes", "Pinturas", "Pintura sobre madeira de demolição", "Torres de igreja colonial, casario de telhados vermelhos descendo o vale, serras verdes no horizonte — e tucanos e ipês em primeiro plano.\n\nFoi em Tiradentes, no início dos anos 90, que Daniel Detomi começou sua trajetória ao lado de artistas como Fernando Pita e Toti, da Oficina de Agosto.\n\nA madeira reaproveitada dá à pintura uma profundidade que tela nenhuma tem: os veios atravessam as montanhas e as juntas das tábuas marcam os planos da paisagem."),
    en: wt("Tiradentes", "Paintings", "Painting on demolition wood", "Colonial church towers, houses with red roofs descending the valley, green mountains on the horizon — and toucans and ipês in the foreground.\n\nIt was in Tiradentes, in the early 1990s, that Daniel Detomi began his path alongside artists such as Fernando Pita and Toti from Oficina de Agosto.\n\nReclaimed wood gives the painting a depth canvas cannot offer: the grain crosses the mountains and the joints between boards mark the planes of the landscape."),
    es: wt("Tiradentes", "Pinturas", "Pintura sobre madera de demolición", "Torres de iglesia colonial, caserío de techos rojos descendiendo por el valle, sierras verdes en el horizonte — y tucanes e ipês en primer plano.\n\nFue en Tiradentes, a comienzos de los años 90, donde Daniel Detomi inició su trayectoria junto a artistas como Fernando Pita y Toti, de la Oficina de Agosto.\n\nLa madera reutilizada da a la pintura una profundidad que ningún lienzo tiene: las vetas atraviesan las montañas y las juntas de las tablas marcan los planos del paisaje."),
    ar: wt("Tiradentes", "لوحات", "رسم على خشب هدم", "أبراج كنائس استعمارية وبيوت بأسقف حمراء تنحدر في الوادي وجبال خضراء في الأفق، مع طيور الطوقان وأشجار الإيبيه في المقدمة.\n\nفي تيرادنتيس، في مطلع التسعينيات، بدأ دانيال ديتومي مساره إلى جانب فنانين مثل فرناندو بيتا وتوتي من Oficina de Agosto.\n\nيمنح الخشب المعاد استخدامه اللوحة عمقًا لا يملكه القماش: العروق تعبر الجبال وفواصل الألواح تحدد مستويات المشهد."),
  },
  "noite-tropical": {
    pt: wt("Noite Tropical", "Pinturas", "Pintura sobre tela", "Um rio de vitórias-régias sob a lua cheia: figuras humanas, helicônias vermelhas, peixes e botos dividem a água numa cena entre o sonho e o mito amazônico.\n\nÉ o Brasil imaginário de Detomi em sua forma mais lírica — a natureza não como cenário, mas como personagem.\n\nUma tela que pede parede ampla e tempo de contemplação."),
    en: wt("Noite Tropical", "Paintings", "Painting on canvas", "A river of giant water lilies under the full moon: human figures, red heliconias, fish and river dolphins share the water in a scene between dream and Amazonian myth.\n\nIt is Detomi's imagined Brazil at its most lyrical — nature not as scenery, but as character.\n\nA canvas that asks for a generous wall and time for contemplation."),
    es: wt("Noite Tropical", "Pinturas", "Pintura sobre lienzo", "Un río de victorias regias bajo la luna llena: figuras humanas, heliconias rojas, peces y botos comparten el agua en una escena entre el sueño y el mito amazónico.\n\nEs el Brasil imaginario de Detomi en su forma más lírica — la naturaleza no como escenario, sino como personaje.\n\nUn lienzo que pide una pared amplia y tiempo de contemplación."),
    ar: wt("Noite Tropical", "لوحات", "رسم على قماش", "نهر من زنابق الماء العملاقة تحت القمر المكتمل: شخصيات بشرية وهليكونيا حمراء وأسماك ودلافين نهرية تتقاسم الماء في مشهد بين الحلم والأسطورة الأمازونية.\n\nإنها برازيل ديتومي المتخيلة في أكثر صورها غنائية: الطبيعة ليست خلفية بل شخصية.\n\nلوحة تحتاج إلى جدار واسع ووقت للتأمل."),
  },
  cupido: {
    pt: wt("Cupido", "Pinturas", "Pintura sobre tábuas de demolição", "Um cupido de asas azuladas se contorce sobre as nuvens, arco esticado — pintado sobre tábuas de demolição cujas juntas atravessam o corpo do personagem como um afresco descoberto sob a parede.\n\nDetomi não esconde as marcas da madeira: compõe sobre elas. Cada falha da tábua vira sombra, nuvem ou contorno.\n\nRomantismo e reúso na mesma peça. Nenhuma tábua se repete; cada Cupido é único."),
    en: wt("Cupido", "Paintings", "Painting on demolition boards", "A cupid with bluish wings twists above the clouds, bow drawn — painted on demolition boards whose joints cross the figure like a fresco uncovered beneath a wall.\n\nDetomi does not hide the marks of the wood: he composes with them. Each flaw becomes shadow, cloud or contour.\n\nRomanticism and reuse in the same piece. No board repeats; each Cupid is unique."),
    es: wt("Cupido", "Pinturas", "Pintura sobre tablas de demolición", "Un cupido de alas azuladas se retuerce sobre las nubes, con el arco tensado — pintado sobre tablas de demolición cuyas juntas atraviesan el cuerpo del personaje como un fresco descubierto bajo la pared.\n\nDetomi no oculta las marcas de la madera: compone sobre ellas. Cada falla de la tabla se vuelve sombra, nube o contorno.\n\nRomanticismo y reúso en la misma pieza. Ninguna tabla se repite; cada Cupido es único."),
    ar: wt("Cupido", "لوحات", "رسم على ألواح خشب هدم", "كيوبيد بأجنحة زرقاء يلتف فوق الغيوم وقوسه مشدود، مرسوم على ألواح خشب هدم تعبر فواصلها جسد الشخصية كأنها فريسكو كُشف تحت الجدار.\n\nلا يخفي ديتومي آثار الخشب بل يؤلف فوقها. كل عيب في اللوح يتحول إلى ظل أو غيمة أو حد.\n\nرومانسية وإعادة استخدام في قطعة واحدة. لا يتكرر أي لوح؛ كل كيوبيد فريد."),
  },
  cocar: {
    pt: wt("Cocar", "Esculturas", "Papel machê e plumária pintada", "Cabeça em papel machê com cocar multicolorido — homenagem direta aos povos originários do Brasil. O rosto em terracota é atravessado por grafismos negros; acima, o cocar explode em centenas de varetas pintadas fio a fio.\n\nCamadas de papel reaproveitado são empastadas, moldadas e lixadas até ganharem a anatomia do rosto. Depois, cada grafismo é traçado à mão, sem molde.\n\nO cocar é símbolo de honra e liderança. Presença escultural que transforma uma sala inteira."),
    en: wt("Cocar", "Sculptures", "Papier-mâché and painted featherwork", "A papier-mâché head with a multicolored headdress — a direct homage to Brazil's Indigenous peoples. The terracotta face is crossed by black graphic marks; above it, the headdress bursts into hundreds of rods painted one by one.\n\nLayers of reused paper are pasted, molded and sanded until they gain the anatomy of the face. Then each graphic mark is drawn by hand, without a stencil.\n\nThe headdress is a symbol of honor and leadership. A sculptural presence that transforms an entire room."),
    es: wt("Cocar", "Esculturas", "Papel maché y plumaria pintada", "Cabeza en papel maché con tocado multicolor — homenaje directo a los pueblos originarios de Brasil. El rostro de terracota está atravesado por grafismos negros; arriba, el tocado explota en cientos de varillas pintadas una a una.\n\nCapas de papel reutilizado se empastan, moldean y lijan hasta ganar la anatomía del rostro. Después, cada grafismo se traza a mano, sin molde.\n\nEl tocado es símbolo de honor y liderazgo. Una presencia escultórica que transforma una sala entera."),
    ar: wt("Cocar", "منحوتات", "ورق معجون وريش مطلي", "رأس من الورق المعجون مع غطاء رأس متعدد الألوان؛ تحية مباشرة للشعوب الأصلية في البرازيل. يعبر الوجه الترابي رسم أسود، وفوقه ينفجر الغطاء في مئات العيدان المرسومة واحدة تلو الأخرى.\n\nتُلصق طبقات من الورق المعاد استخدامه وتُشكّل وتُصقل حتى تكتسب تشريح الوجه، ثم تُرسم كل علامة يدويًا بلا قالب.\n\nغطاء الرأس رمز للشرف والقيادة، وحضور نحتي يغيّر الغرفة كلها."),
  },
  guardiao: {
    pt: wt("Guardião", "Esculturas", "Papel machê, cocar de varetas pintadas", "Busto em papel machê sobre base listrada, com pintura corporal geométrica e cocar de varetas que irradiam em todas as direções como um sol.\n\nAs varetas são recortadas, enroladas e pintadas uma a uma em faixas de amarelo, preto e vermelho — dias de trabalho para uma única peça.\n\nO olhar lateral dá à peça a sensação de vigia: um guardião que acompanha o ambiente."),
    en: wt("Guardião", "Sculptures", "Papier-mâché and headdress of painted rods", "A papier-mâché bust on a striped base, with geometric body painting and a headdress of rods radiating in every direction like a sun.\n\nThe rods are cut, rolled and painted one by one in bands of yellow, black and red — days of work for a single piece.\n\nThe sideward gaze gives the work a watchful feeling: a guardian that follows the room."),
    es: wt("Guardião", "Esculturas", "Papel maché y tocado de varillas pintadas", "Busto en papel maché sobre base rayada, con pintura corporal geométrica y tocado de varillas que irradian en todas las direcciones como un sol.\n\nLas varillas se cortan, enrollan y pintan una a una en franjas de amarillo, negro y rojo — días de trabajo para una sola pieza.\n\nLa mirada lateral da a la obra una sensación de vigilancia: un guardián que acompaña el ambiente."),
    ar: wt("Guardião", "منحوتات", "ورق معجون وغطاء من عيدان مطلية", "تمثال نصفي من الورق المعجون على قاعدة مخططة، مع رسم جسدي هندسي وغطاء رأس من عيدان تشع في كل الاتجاهات كالشمس.\n\nتُقص العيدان وتُلف وتُطلى واحدة تلو الأخرى بخطوط صفراء وسوداء وحمراء، في عمل يستغرق أيامًا لقطعة واحدة.\n\nالنظرة الجانبية تمنح القطعة إحساس الحراسة: حارس يرافق المكان."),
  },
  araras: {
    pt: wt("Araras", "Esculturas", "Escultura de parede pintada à mão", "Duas araras-azuis e uma arara-vermelha em escultura de parede: corpo, asas e cauda são peças separadas, sobrepostas para criar relevo real.\n\nAs penas são incisas e pintadas individualmente — a plumagem muda com a luz do ambiente ao longo do dia.\n\nA arara-azul quase desapareceu pela destruição do habitat. Pendurar estas aves na parede é decorar com significado."),
    en: wt("Araras", "Sculptures", "Hand-painted wall sculpture", "Two blue macaws and one red macaw in a wall sculpture: body, wings and tail are separate pieces, layered to create real relief.\n\nThe feathers are incised and painted individually — the plumage changes with the room's light throughout the day.\n\nThe hyacinth macaw nearly disappeared through habitat destruction. Hanging these birds on the wall is decoration with meaning."),
    es: wt("Araras", "Esculturas", "Escultura de pared pintada a mano", "Dos guacamayos azules y uno rojo en escultura de pared: cuerpo, alas y cola son piezas separadas, superpuestas para crear relieve real.\n\nLas plumas están incisas y pintadas individualmente; el plumaje cambia con la luz del ambiente durante el día.\n\nEl guacamayo azul casi desapareció por la destrucción del hábitat. Colgar estas aves en la pared es decorar con significado."),
    ar: wt("Araras", "منحوتات", "منحوتة جدارية مرسومة يدويًا", "ببغاوان أزرقان وببغاء أحمر في منحوتة جدارية: الجسد والأجنحة والذيل قطع منفصلة متراكبة لتخلق بروزًا حقيقيًا.\n\nنُقشت الريشات ورُسمت كل واحدة على حدة، فيتغير الريش مع ضوء المكان خلال اليوم.\n\nكاد الببغاء الأزرق أن يختفي بسبب تدمير موطنه. تعليق هذه الطيور على الجدار هو تزيين ذو معنى."),
  },
  ancionais: {
    pt: wt("Ancionais", "Galeria a Céu Aberto", "Papel machê em grande escala, uso externo", "Cinco rostos monumentais em papel machê repousam lado a lado na borda do barranco, com a mata atlântica fechando o fundo — cada um com expressão própria, entre o riso e a meditação.\n\nSão obras feitas para o tempo: chuva, sol e musgo vão acrescentando camadas novas à pele de cada rosto. O envelhecimento não estraga a obra — ele a continua.\n\nNo jardim do ateliê, a arte não fica atrás de vidro: vive no chão, na grama, entre as árvores."),
    en: wt("Ancionais", "Open-Air Gallery", "Large-scale outdoor papier-mâché", "Five monumental papier-mâché faces rest side by side at the edge of the hillside, with the Atlantic forest closing the background — each with its own expression, between laughter and meditation.\n\nThey are works made for time: rain, sun and moss add new layers to the skin of each face. Aging does not damage the work — it continues it.\n\nIn the studio garden, art is not behind glass: it lives on the ground, in the grass, among the trees."),
    es: wt("Ancionais", "Galería al Aire Libre", "Papel maché a gran escala, uso exterior", "Cinco rostros monumentales de papel maché descansan lado a lado al borde del barranco, con la mata atlántica cerrando el fondo — cada uno con expresión propia, entre la risa y la meditación.\n\nSon obras hechas para el tiempo: lluvia, sol y musgo van agregando nuevas capas a la piel de cada rostro. El envejecimiento no estropea la obra; la continúa.\n\nEn el jardín del atelier, el arte no queda detrás del vidrio: vive en el suelo, en la hierba, entre los árboles."),
    ar: wt("Ancionais", "معرض في الهواء الطلق", "ورق معجون كبير الحجم للاستخدام الخارجي", "خمسة وجوه ضخمة من الورق المعجون تستقر جنبًا إلى جنب على حافة المنحدر، والغابة الأطلسية تغلق الخلفية؛ لكل وجه تعبيره بين الضحك والتأمل.\n\nإنها أعمال صُنعت للزمن: المطر والشمس والطحلب يضيفون طبقات جديدة إلى جلد كل وجه. الشيخوخة لا تفسد العمل بل تواصله.\n\nفي حديقة المرسم لا يبقى الفن خلف الزجاج: يعيش على الأرض وفي العشب وبين الأشجار."),
  },
  capivaras: {
    pt: wt("Capivaras", "Galeria a Céu Aberto", "Conjunto em metal recortado e pintado", "Capivaras de todos os tamanhos pastam sobre as pedras, um veado amamenta o filhote malhado e um macaco amarelo balança na coluna da varanda.\n\nCada animal é recortado em metal de reúso e pintado em tons de palha e ferrugem que se misturam ao verde do gramado.\n\nOs conjuntos são feitos sob medida — o cliente escolhe espécies, quantidades e tamanhos. O jardim vira um palco que muda quando o dono quiser."),
    en: wt("Capivaras", "Open-Air Gallery", "Cut and painted metal ensemble", "Capybaras of all sizes graze on the stones, a deer nurses its spotted fawn and a yellow monkey swings on the veranda column.\n\nEach animal is cut from reclaimed metal and painted in straw and rust tones that blend with the green lawn.\n\nThe ensembles are made to order — the client chooses species, quantities and sizes. The garden becomes a stage that can change whenever its owner wishes."),
    es: wt("Capivaras", "Galería al Aire Libre", "Conjunto en metal recortado y pintado", "Capibaras de todos los tamaños pastan sobre las piedras, una venada amamanta a su cría manchada y un mono amarillo se balancea en la columna de la varanda.\n\nCada animal está recortado en metal reutilizado y pintado en tonos paja y óxido que se mezclan con el verde del césped.\n\nLos conjuntos se hacen a medida: el cliente elige especies, cantidades y tamaños. El jardín se vuelve un escenario que cambia cuando el dueño quiera."),
    ar: wt("Capivaras", "معرض في الهواء الطلق", "مجموعة من معدن مقصوص ومطلي", "كابيبارا بأحجام مختلفة ترعى فوق الحجارة، وغزال يرضع صغيره المرقط، وقرد أصفر يتأرجح على عمود الشرفة.\n\nكل حيوان مقصوص من معدن معاد استخدامه ومطلي بدرجات القش والصدأ التي تمتزج بخضرة العشب.\n\nتُصنع المجموعات حسب الطلب؛ يختار العميل الأنواع والكميات والأحجام. تتحول الحديقة إلى مسرح يتغير متى أراد صاحبها."),
  },
  veados: {
    pt: wt("Veados", "Galeria a Céu Aberto", "Metal de reúso, asas em chapa pintada", "Três veados-campeiros atravessam o jardim entre bromélias vermelhas — e, acima de tudo, um par de asas brancas abertas paira sobre a cena.\n\nAs asas, em chapa branca, têm cada pena recortada e sobreposta: leveza construída em material pesado.\n\nA cena mistura documento e sonho — os veados são os que habitam o cerrado ao redor de Tiradentes; as asas são o desejo de proteção sobre eles."),
    en: wt("Veados", "Open-Air Gallery", "Reclaimed metal and painted sheet wings", "Three marsh deer cross the garden among red bromeliads — and above everything, a pair of open white wings hovers over the scene.\n\nThe wings, made from white sheet metal, have each feather cut and layered: lightness built from heavy material.\n\nThe scene mixes document and dream — the deer are those that inhabit the cerrado around Tiradentes; the wings are the wish to protect them."),
    es: wt("Veados", "Galería al Aire Libre", "Metal reutilizado, alas en chapa pintada", "Tres venados campeiros atraviesan el jardín entre bromelias rojas — y, sobre todo, un par de alas blancas abiertas flota sobre la escena.\n\nLas alas, en chapa blanca, tienen cada pluma recortada y superpuesta: ligereza construida con material pesado.\n\nLa escena mezcla documento y sueño — los venados son los que habitan el cerrado alrededor de Tiradentes; las alas son el deseo de protección sobre ellos."),
    ar: wt("Veados", "معرض في الهواء الطلق", "معدن معاد استخدامه وأجنحة من صفيح مطلي", "ثلاثة غزلان تعبر الحديقة بين البروميليا الحمراء، وفوق المشهد كله يحوم زوج من الأجنحة البيضاء المفتوحة.\n\nالأجنحة المصنوعة من صفيح أبيض لها كل ريشة مقصوصة ومركبة: خفة مبنية من مادة ثقيلة.\n\nيمزج المشهد بين التوثيق والحلم؛ الغزلان هي سكان السيرادو حول تيرادنتيس، والأجنحة رغبة في حمايتها."),
  },
  dalmata: {
    pt: wt("Dálmata", "Circo & Forma", "Pintura sobre fundo xadrez óptico", "Um dálmata em pose alerta, língua de fora, sobre um fundo xadrez que ondula e engana os olhos — o padrão entorta atrás do cachorro como se a parede respirasse.\n\nO xadrez é pintado com precisão matemática e depois distorcido de propósito: a ilusão de movimento numa superfície parada.\n\nRigor geométrico quebrado pela vida. O ateliê aceita retratos de pets sob encomenda com a mesma técnica."),
    en: wt("Dálmata", "Circus & Form", "Painting on optical chessboard background", "A dalmatian in an alert pose, tongue out, over a chessboard background that ripples and tricks the eye — the pattern bends behind the dog as if the wall were breathing.\n\nThe grid is painted with mathematical precision and then deliberately distorted: the illusion of movement on a still surface.\n\nGeometric rigor broken by life. The studio accepts commissioned pet portraits using the same technique."),
    es: wt("Dálmata", "Circo y Forma", "Pintura sobre fondo ajedrezado óptico", "Un dálmata en pose alerta, lengua afuera, sobre un fondo ajedrezado que ondula y engaña los ojos — el patrón se tuerce detrás del perro como si la pared respirara.\n\nEl ajedrezado está pintado con precisión matemática y luego distorsionado a propósito: la ilusión de movimiento en una superficie quieta.\n\nRigor geométrico quebrado por la vida. El atelier acepta retratos de mascotas por encargo con la misma técnica."),
    ar: wt("Dálmata", "السيرك والشكل", "رسم على خلفية شطرنجية بصرية", "كلب دلماسي في وضع يقظ ولسانه خارج فمه فوق خلفية شطرنجية تتموج وتخدع العين؛ ينحني النمط خلف الكلب كأن الجدار يتنفس.\n\nرُسمت الشبكة بدقة رياضية ثم شُوهت عمدًا: وهم الحركة على سطح ثابت.\n\nصرامة هندسية تكسرها الحياة. يقبل المرسم طلبات بورتريه للحيوانات الأليفة بالتقنية نفسها."),
  },
  "tenis-xadrez": {
    pt: wt("Tênis Xadrez", "Circo & Forma", "Pintura, ilusão de ótica", "Um tênis de cadarços soltos flutua sobre uma grade xadrez que se curva e se abre — pop art e ilusão de ótica num mesmo quadro.\n\nA obra mostra o outro lado de Detomi: o artista de formação técnica rigorosa, interessado pela percepção visual.\n\nO mesmo olhar que observa a natureza com precisão é o que deconstrói uma grade xadrez."),
    en: wt("Tênis Xadrez", "Circus & Form", "Painting and optical illusion", "A sneaker with loose laces floats above a chessboard grid that bends and opens — pop art and optical illusion in the same picture.\n\nThe work reveals another side of Detomi: the artist with rigorous technical training and a deep interest in visual perception.\n\nThe same gaze that observes nature precisely is the one that deconstructs a chessboard grid."),
    es: wt("Tênis Xadrez", "Circo y Forma", "Pintura e ilusión óptica", "Un tenis de cordones sueltos flota sobre una retícula ajedrezada que se curva y se abre — pop art e ilusión óptica en un mismo cuadro.\n\nLa obra muestra otro lado de Detomi: el artista de formación técnica rigurosa, interesado por la percepción visual.\n\nLa misma mirada que observa la naturaleza con precisión es la que deconstruye una cuadrícula ajedrezada."),
    ar: wt("Tênis Xadrez", "السيرك والشكل", "رسم وخداع بصري", "حذاء رياضي بأربطة مفكوكة يطفو فوق شبكة شطرنجية تنحني وتنفتح؛ فن بوب وخداع بصري في لوحة واحدة.\n\nيكشف العمل جانبًا آخر من ديتومي: فنانًا ذا تدريب تقني صارم واهتمام عميق بالإدراك البصري.\n\nالنظرة نفسها التي تراقب الطبيعة بدقة هي التي تفكك شبكة شطرنجية."),
  },
  arlequins: {
    pt: wt("Arlequins", "Circo & Forma", "Pintura emoldurada, série circo", "Palhaços e arlequins equilibristas emoldurados, entre bandeirinhas de festa e céus de algodão — o artista como performer, como equilibrista sobre a bola vermelha.\n\nA série é uma reflexão sobre o próprio ofício: criar é sempre um número de circo, feito sem rede.\n\nConjuntos de molduras podem ser compostos sob encomenda."),
    en: wt("Arlequins", "Circus & Form", "Framed painting, circus series", "Clowns and balancing harlequins framed among festival flags and cotton-like skies — the artist as performer, as an acrobat on the red ball.\n\nThe series reflects on the craft itself: creating is always a circus act, performed without a net.\n\nSets of frames can be composed by commission."),
    es: wt("Arlequins", "Circo y Forma", "Pintura enmarcada, serie circo", "Payasos y arlequines equilibristas enmarcados, entre banderines de fiesta y cielos de algodón — el artista como performer, como equilibrista sobre la bola roja.\n\nLa serie reflexiona sobre el propio oficio: crear siempre es un número de circo, hecho sin red.\n\nLos conjuntos de marcos pueden componerse por encargo."),
    ar: wt("Arlequins", "السيرك والشكل", "رسم مؤطر، سلسلة السيرك", "مهرجون وهارلكين متوازنون داخل إطارات، بين رايات احتفال وسماء قطنية؛ الفنان كمؤدٍ وبهلوان فوق الكرة الحمراء.\n\nتتأمل السلسلة في المهنة نفسها: الخلق دائمًا عرض سيرك يُنجز بلا شبكة.\n\nيمكن تركيب مجموعات الإطارات حسب الطلب."),
  },
  "lobo-guara": {
    pt: wt("Lobo-Guará", "Recortes", "Recorte em chapas de metal de reúso", "O lobo-guará atravessa o jardim em passo largo: pelagem vermelho-alaranjada pintada fio a fio, gola clara, pernas negras como meias.\n\nRecorte em chapa de metal de reúso: desenho em escala real, corte, dobra sutil para dar volume, e pintura com pincel fino seguindo a direção real da pelagem.\n\nO maior canídeo da América do Sul, símbolo do cerrado mineiro — arte que une emoção e defesa ambiental."),
    en: wt("Lobo-Guará", "Cut-Outs", "Cut-out from reclaimed metal sheets", "The maned wolf crosses the garden in a long stride: reddish-orange fur painted strand by strand, pale collar, black legs like stockings.\n\nCut from reclaimed metal sheet: life-size drawing, cutting, subtle bending for volume and fine-brush painting following the real direction of the fur.\n\nThe largest canid in South America, symbol of the cerrado in Minas Gerais — art joining emotion and environmental defense."),
    es: wt("Lobo-Guará", "Recortes", "Recorte en chapas de metal reutilizado", "El lobo de crin cruza el jardín con paso largo: pelaje rojo anaranjado pintado pelo a pelo, gola clara, patas negras como medias.\n\nRecorte en chapa de metal reutilizado: dibujo a escala real, corte, doblez sutil para dar volumen y pintura con pincel fino siguiendo la dirección real del pelaje.\n\nEl mayor cánido de Sudamérica, símbolo del cerrado mineiro — arte que une emoción y defensa ambiental."),
    ar: wt("Lobo-Guará", "قصاصات معدنية", "قص من صفائح معدنية معاد استخدامها", "يعبر ذئب الغوارا الحديقة بخطوة واسعة: فراء أحمر برتقالي مرسوم خصلة خصلة، ياقة فاتحة، وسيقان سوداء كالجوارب.\n\nقص من صفيحة معدنية معاد استخدامها: رسم بالحجم الحقيقي، وقص، وانحناء خفيف للحجم، وتلوين بفرشاة دقيقة مع اتجاه الفراء الحقيقي.\n\nأكبر كلبيات أمريكا الجنوبية ورمز سيرادو ميناس جيرايس؛ فن يجمع العاطفة والدفاع البيئي."),
  },
  onca: {
    pt: wt("Onça", "Recortes", "Metal recortado e pintado", "A onça-pintada avança em direção a quem olha, corpo baixo e mandíbula aberta — dezenas de rosetas desenhadas uma a uma, nenhuma igual à outra.\n\nPrimeiro o dourado-ocre do fundo, depois as rosetas, por último focinho, olhos esverdeados e garras: o trabalho mais minucioso do repertório.\n\nOnde a onça está, o ecossistema inteiro está de pé. A postura do animal diz tudo, sem legenda."),
    en: wt("Onça", "Cut-Outs", "Cut and painted metal", "The jaguar advances toward the viewer, body low and jaw open — dozens of rosettes drawn one by one, none identical to another.\n\nFirst the golden ocher base, then the rosettes, finally the muzzle, greenish eyes and claws: the most meticulous work in the repertoire.\n\nWhere the jaguar lives, the whole ecosystem stands. The animal's posture says everything without a caption."),
    es: wt("Onça", "Recortes", "Metal recortado y pintado", "El jaguar avanza hacia quien mira, cuerpo bajo y mandíbula abierta — decenas de rosetas dibujadas una a una, ninguna igual a otra.\n\nPrimero el dorado ocre del fondo, después las rosetas, por último hocico, ojos verdosos y garras: el trabajo más minucioso del repertorio.\n\nDonde está el jaguar, todo el ecosistema está de pie. La postura del animal lo dice todo, sin leyenda."),
    ar: wt("Onça", "قصاصات معدنية", "معدن مقصوص ومطلي", "يتقدم النمر المرقط نحو الناظر، جسده منخفض وفكه مفتوح؛ عشرات الوريدات مرسومة واحدة تلو الأخرى، ولا واحدة تشبه الأخرى.\n\nأولًا الخلفية الذهبية المغرة، ثم الوريدات، وأخيرًا الخطم والعيون الخضراء والمخالب: أكثر أعمال المجموعة دقة.\n\nحيث يوجد النمر يبقى النظام البيئي كله قائمًا. وضعية الحيوان تقول كل شيء بلا تعليق."),
  },
  seriemas: {
    pt: wt("Seriemas", "Recortes", "Metal recortado, conjunto de aves", "Seriemas de asas entreabertas e um bando de filhotes escuros bicando o capim entre flores amarelas — uma cena de vida, não uma fileira de objetos.\n\nAs penas das asas e da cauda são desenhadas em relevo e pintadas na paleta exata da ave: castanho, palha e pernas vermelhas.\n\nA ave-símbolo do cerrado mineiro, cujo canto atravessa os campos de Tiradentes ao amanhecer."),
    en: wt("Seriemas", "Cut-Outs", "Cut metal bird ensemble", "Seriemas with half-open wings and a group of dark chicks pecking the grass among yellow flowers — a scene of life, not a row of objects.\n\nThe wing and tail feathers are drawn in relief and painted in the bird's precise palette: brown, straw and red legs.\n\nThe emblematic bird of the cerrado in Minas Gerais, whose call crosses the fields of Tiradentes at dawn."),
    es: wt("Seriemas", "Recortes", "Metal recortado, conjunto de aves", "Seriemas de alas entreabiertas y un grupo de polluelos oscuros picando el pasto entre flores amarillas — una escena de vida, no una fila de objetos.\n\nLas plumas de las alas y la cola están dibujadas en relieve y pintadas en la paleta exacta del ave: castaño, paja y patas rojas.\n\nEl ave símbolo del cerrado mineiro, cuyo canto atraviesa los campos de Tiradentes al amanecer."),
    ar: wt("Seriemas", "قصاصات معدنية", "مجموعة طيور من معدن مقصوص", "طيور سيريما بأجنحة نصف مفتوحة ومجموعة من الفراخ الداكنة تنقر العشب بين زهور صفراء؛ مشهد حياة لا صف أشياء.\n\nرُسم ريش الأجنحة والذيل ببروز وطُلي بألوان الطائر الدقيقة: بني وقشي وسيقان حمراء.\n\nطائر رمز للسيرادو في ميناس جيرايس، يعبر صوته حقول تيرادنتيس عند الفجر."),
  },
  "guardioes-da-encosta": {
    pt: wt("Guardiões da Encosta", "Arte Ambiental", "Papel machê monumental in situ", "Três rostos monumentais emergem da encosta entre samambaias e troncos, vigiados por uma onça recortada no alto do barranco.\n\nA obra só existe plenamente em relação ao lugar: a terra, a vegetação e a luz de Tiradentes são parte da composição.\n\nArte ambiental é a face mais radical do ateliê — a paisagem como moldura e como matéria."),
    en: wt("Guardiões da Encosta", "Environmental Art", "Monumental in-situ papier-mâché", "Three monumental faces emerge from the hillside among ferns and trunks, watched over by a cut-out jaguar at the top of the slope.\n\nThe work only fully exists in relation to the place: the earth, vegetation and light of Tiradentes are part of the composition.\n\nEnvironmental art is the studio's most radical face — landscape as frame and as material."),
    es: wt("Guardiões da Encosta", "Arte Ambiental", "Papel maché monumental in situ", "Tres rostros monumentales emergen de la ladera entre helechos y troncos, vigilados por un jaguar recortado en lo alto del barranco.\n\nLa obra solo existe plenamente en relación con el lugar: la tierra, la vegetación y la luz de Tiradentes son parte de la composición.\n\nEl arte ambiental es la cara más radical del atelier — el paisaje como marco y como materia."),
    ar: wt("Guardiões da Encosta", "فن بيئي", "ورق معجون ضخم في الموقع", "تخرج ثلاثة وجوه ضخمة من المنحدر بين السراخس والجذوع، يراقبها نمر مقصوص في أعلى الجرف.\n\nلا يكتمل العمل إلا بعلاقته بالمكان: الأرض والنبات وضوء تيرادنتيس جزء من التكوين.\n\nالفن البيئي هو الوجه الأكثر جذرية في المرسم؛ المشهد إطار ومادة في آن واحد."),
  },
  vigia: {
    pt: wt("Vigia", "Arte Ambiental", "Papel machê e metal de reúso", "Entre agaves azul-esverdeadas, uma máscara de grafismos negros observa o jardim enquanto uma seriema em metal caminha diante dela.\n\nO encontro que define o trabalho de Detomi: os povos originários e a fauna do cerrado no mesmo quadro.\n\nA máscara vigia, a ave patrulha — narrativa silenciosa que transforma cantos de jardim em galeria viva."),
    en: wt("Vigia", "Environmental Art", "Papier-mâché and reclaimed metal", "Among blue-green agaves, a mask with black graphic markings watches the garden while a metal seriema walks before it.\n\nThe encounter defines Detomi's work: Indigenous peoples and the fauna of the cerrado within the same living frame.\n\nThe mask watches, the bird patrols — a silent narrative that turns corners of the garden into a living gallery."),
    es: wt("Vigia", "Arte Ambiental", "Papel maché y metal reutilizado", "Entre agaves azul verdosos, una máscara de grafismos negros observa el jardín mientras una seriema de metal camina delante de ella.\n\nEl encuentro que define el trabajo de Detomi: los pueblos originarios y la fauna del cerrado en un mismo cuadro.\n\nLa máscara vigila, el ave patrulla — narrativa silenciosa que transforma rincones del jardín en galería viva."),
    ar: wt("Vigia", "فن بيئي", "ورق معجون ومعدن معاد استخدامه", "بين نباتات أغاف زرقاء خضراء، يراقب قناع بعلامات سوداء الحديقة بينما تمشي أمامه سيريما معدنية.\n\nهذا اللقاء يعرّف عمل ديتومي: الشعوب الأصلية وحيوانات السيرادو في إطار حي واحد.\n\nالقناع يراقب والطائر يجوب؛ سرد صامت يحول زوايا الحديقة إلى معرض حي."),
  },
  tucano: {
    pt: wt("Tucano", "Recortes", "Recorte em chapa, pintura à mão", "Um tucano-toco em tamanho monumental ocupa a parede: bico alaranjado pintado em degradê, olho azul-elétrico e plumagem negra recortada em chapa.\n\nNo bico, uma surpresa: a sequência da evolução humana gravada em silhueta — o passado caminhando sobre o símbolo da fauna brasileira.\n\nPeça de parede de grande impacto, feita para áreas internas ou varandas protegidas. O ateliê produz outras espécies sob encomenda."),
    en: wt("Tucano", "Cut-Outs", "Sheet-metal cut-out, hand painting", "A monumental toco toucan occupies the wall: orange beak painted in gradient, electric-blue eye and black plumage cut from sheet metal.\n\nOn the beak, a surprise: the sequence of human evolution engraved in silhouette — the past walking across a symbol of Brazilian fauna.\n\nA wall piece of strong impact, made for interiors or protected verandas. The studio produces other species by commission."),
    es: wt("Tucano", "Recortes", "Recorte en chapa, pintura a mano", "Un tucán toco de tamaño monumental ocupa la pared: pico anaranjado pintado en degradado, ojo azul eléctrico y plumaje negro recortado en chapa.\n\nEn el pico, una sorpresa: la secuencia de la evolución humana grabada en silueta — el pasado caminando sobre el símbolo de la fauna brasileña.\n\nPieza de pared de gran impacto, hecha para interiores o verandas protegidas. El atelier produce otras especies por encargo."),
    ar: wt("Tucano", "قصاصات معدنية", "قص من صفيح ورسم يدوي", "طوقان توكو بحجم ضخم يحتل الجدار: منقار برتقالي مرسوم بتدرج، عين زرقاء كهربائية وريش أسود مقصوص من الصفيح.\n\nعلى المنقار مفاجأة: تسلسل تطور الإنسان محفور كظلال؛ الماضي يمشي فوق رمز من رموز الحيوان البرازيلي.\n\nقطعة جدارية ذات أثر قوي، للمساحات الداخلية أو الشرفات المحمية. ينتج المرسم أنواعًا أخرى حسب الطلب."),
  },
  "dalmata-xadrez": {
    pt: wt("Dálmata no Xadrez", "Circo & Forma", "Painel pintado, xadrez óptico", "O dálmata em corpo inteiro sobre o xadrez que ondula — a versão em painel da série de ilusão de ótica do ateliê.\n\nCada mancha é pintada individualmente e o fundo xadrez é calculado para entortar atrás do cachorro, criando a sensação de parede viva.\n\nRetratos de pets sob encomenda com a mesma técnica: o ateliê trabalha a partir de fotos do animal."),
    en: wt("Dálmata no Xadrez", "Circus & Form", "Painted panel, optical chessboard", "The full-body dalmatian over a rippling chessboard — the panel version of the studio's optical illusion series.\n\nEach spot is painted individually and the chessboard background is calculated to bend behind the dog, creating the feeling of a living wall.\n\nCommissioned pet portraits with the same technique: the studio works from photos of the animal."),
    es: wt("Dálmata no Xadrez", "Circo y Forma", "Panel pintado, ajedrez óptico", "El dálmata de cuerpo entero sobre el ajedrez que ondula — la versión en panel de la serie de ilusión óptica del atelier.\n\nCada mancha está pintada individualmente y el fondo ajedrezado está calculado para torcerse detrás del perro, creando la sensación de una pared viva.\n\nRetratos de mascotas por encargo con la misma técnica: el atelier trabaja a partir de fotos del animal."),
    ar: wt("Dálmata no Xadrez", "السيرك والشكل", "لوح مرسوم وخلفية شطرنجية بصرية", "الدلماسي بكامل جسده فوق رقعة شطرنجية متموجة؛ نسخة اللوح من سلسلة الخداع البصري في المرسم.\n\nتُرسم كل بقعة على حدة وتُحسب الخلفية الشطرنجية لتنحني خلف الكلب، فتخلق إحساس جدار حي.\n\nبورتريهات حيوانات أليفة حسب الطلب بالتقنية نفسها؛ يعمل المرسم انطلاقًا من صور الحيوان."),
  },
};
